apiVersion: v2
name: bitbucket-runner-autoscaler
description: Chart for deploying Bitbucket Runner Autoscaler.

type: application

version: 0.3.0
appVersion: 3.9.0

maintainers:
  - name: Labyrinth Labs
    email: contact@lablabs.io
    url: https://lablabs.io
